# This is needed, but should be deployed using ArgoCD
# instead. Plus it is not secured (yet).

# Note: I'm seeing MinIO connection info here, so you will likely need
# to create a NetworkPolicy to allow that communication (because there will
# be a deny-by-default in the namespace).

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hive-metastore
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/hive-metastore-0.1.0.tgz
  targetNamespace: hive-system
  valuesContent: |-
    mariadb:
      auth:
        rootPassword: Q1zx10EMuU21aEgAZm4kJm9DrD0EjjzIYE8y01Ea
        password: Q1zx10EMuU21aEgAZm4kJm9DrD0EjjzIYE8y01Ea
    conf:
      hiveSite:
        fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        fs.s3a.access.key: trino
        fs.s3a.secret.key: Q1zx10EMuU21aEgAZm4kJm9DrD0EjjzIYE8y01Ea
        fs.s3a.endpoint: http://minio.minio-system:9000
        fs.s3a.path.style.access: true
