apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minio
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: minio
  version: 10.1.9
  targetNamespace: minio-system
  valuesContent: |-
    auth:
      rootPassword: Q1zx10EMuU21aEgAZm4kJm9DrD0EjjzIYE8y01Ea
