image:
  repository: bitsondatadev/hive-metastore
  tag: latest
  pullPolicy: IfNotPresent

mariadb:
  auth:
    username: hive
    database: metastore

replicas: 1
resources: {}
conf:
  hiveSite:
    hive_metastore_uris: thrift://hive-metastore:9083
    # if not set, default hive.metastore.warehouse.dir is default to: "hdfs://{{.Release.Name}}-hdfs:8020/user/hive/warehouse"
    # hive.metastore.warehouse.dir:
