apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    {{- include "hiveMetastore.labels" . | nindent 4 }}
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:postgresql://{{ .Release.Name }}-postgresql/metastore?createDatabaseIfNotExist=true</value>
        </property>
        <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>org.postgresql.Driver</value>
        </property>
        <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>{{ .Values.postgresql.auth.username }}</value>
        </property>
        <property>
          <name> javax.jdo.option.ConnectionPassword</name>
          <value>{{ .Values.postgresql.auth.password }}</value>
        </property>
        <property>
          <name>datanucleus.autoCreateSchema</name>
          <value>false</value>
        </property>
        <property>
          <name>metastore.try.direct.sql.ddl</name>
          <value>false</value>
        </property>
        {{- if not (index .Values.conf "hiveSite" "hive.metastore.uris")  }}
        <property>
          <name>hive.metastore.uris</name>
          <value>thrift://{{ include "hiveMetastore.fullname" . }}:9083</value>
        </property>
      {{- end }}
      {{- if not (index .Values.conf "hiveSite" "hive.metastore.warehouse.dir")  }}
      <property>
        <name>metastore.task.threads.always</name>
        <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask</value>
      </property>
      <property>
        <name>metastore.expression.proxy</name>
        <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
      </property>	
    {{- end }}
      {{- if index .Values.conf "hiveSite" }}
      {{- range $key, $value := index .Values.conf "hiveSite" }}
      <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
      {{- end }}
      {{- end }}
    </configuration>