apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: catalogs
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}

  password.db: |
    aaw-capex:$2y$10$mwRt8ejYGnF6A2pg5pYM.u1N0FdGpZBDu7NCsQwqypAIULi8Ve76K
    aaw-fc:$2y$10$gQKB8SJu4oRMGP5Ye0dkq.xq.aQbl50lS3YEuDRxUNTdb/yznS782
    aaw-pssd:$2y$10$Ze1KZrii5eauUYzsszDxTefNJpIl4e1UCK2Dnw5Al9EATH4aVzNiu
    aaw-sedar:$2y$10$fua.5dUfgVuWn3vv.0hsd.45pAUh.sx2GE.1Ap4Jpo6llJ1FHqJ/a
    aaw-sedar-app:$2y$10$0IWEjwm1IBb5V3AloScaO.ag10OVEcEUINmGVeWhcCjIfbuwJtrM.
    admin-zachary-seguin:$2y$10$FA7rz9OAAwKSK/ew89zsAOcpB/7P1lUmJ2x44A5wFIUQfaspqKzWK
    agzero-avhrr:$2y$10$rp2YdeDpiy19T8dZ35VJeO.bzw93B0Le5nfdPxLbt.FrUj1FWEqfm
    agzero-crop-intentions:$2y$10$Sry5kPAtX4icfvGScy0dFuA/cvRDPtX1sENYAx39QxoLmW8/OkBWK
    agzero-march-stocks:$2y$10$nCJiNBx5Kh10N5Av1Lluf.Dir9DkQuwwuyLh.kH2X8zMg1jaA8lu2
    agzero-pig-trace:$2y$10$GFrXSDzwhoq7EKEYe4eleOvXO1D.TNQ/7UCT/.dO3up7yQ4xAvpSm
    agzero-poc:$2y$10$lntNplw8JD9M6.FAgvhhzubQFrpqJUpyXfaV1A5QqSG6msGlrywy.
    agzero-solar-panel:$2y$10$KMnvMwHM6mYA7aTyQvUNN.sQXaW3uwMcFxDu5Pg8uAh5tAtSu7ySy
    agzero-yield-model:$2y$10$CpZch/aqZYNPOPLb19S1xedtIqOrtj/QABRVyE9IUfNJmqTmPKoEq
    andres-solismontero:$2y$10$y6MGImV66ZqxO4Teslwef.JvqcxnaLslIwWNcjl6ryP3uq/lZlC.i
    andrew-scribner:$2y$10$cAtiLhfJUeuiiQ9R.6/6GOs987.5rLBBK0haxiczxlHbXRxjkXImS
    bar:$2y$10$vgDOc.hYdmgBv7Zg7RxYc.7/mOHIId4GMh3rROu5OzLbACgTLTyOy
    bar-rtlbci:$2y$10$XCK.24.KvyEJgmdEMMrhaePag3wZk8FI/UlL5ub.6lulAYYkBX0F.
    benjamin-santos:$2y$10$SuebDKuRbK/nKZ9oRGLdvuP/mxjZenTMQbkbkKb3JQxbMBF0kKABG
    bhavika-sewpal:$2y$10$uGGIjSYDBxRlnXiba0babeYTxeJMe.T.ZAi8SdKm7oVjGiPDaH/1S
    blair-drummond:$2y$10$XbA55EmmTSa/qFRDHY9SnuDBRtWqlxKPaXuHFmGp92l0ch9Qa/CIq
    blair-kubeflow-tests:$2y$10$bG2/p/FvhLtzF4X5eCiVie0zyORKcdNRThHJFjVKVhkZuX7EyYx7K
    blair-shared:$2y$10$0tMufrT27MSY.gckikqKzO4OP2A0otXjEHZd8eizgYSO1KsfUARDq
    bob-ross-pics-rise-again:$2y$10$6c43dcmmMzsqj9quXrjEwepY2TV40AJIy8woX3ZUvQs/6zHbj51Ue
    brendan-gadd:$2y$10$J4rynvasygGFcRvUDgkwT.n2Kc2IBoYSF5fo2vbBwn.GaDqzDwOnK
    brian-chen:$2y$10$IleGyxN2CYybGCtXyeSRSe0veEv7jt0NjpXbtjgEgw/1B0KB.DEE.
    bryan-paget:$2y$10$es1Jp8gOH/JpimJdIUXiDu.wZ2xYNTWqBOM7dvYWQzzuVQxgniSqO
    bryanpaget:$2y$10$nnP1oGJNM5ZDmtjodDSUNeKwjJOiRrFw8JcRE9R0YqT950uBgqf6e
    building-feat-ext:$2y$10$RDHsrKjFILMw2FL6qIws8OucSYzeVFIRmGpmb6mHBQIRzozobJ2qi
    canary:$2y$10$LjVZlJ.gbUyFXuiL21Vtb.NdCmUsAAazmSUD12wtUx1Kzecd2XDNa
    ccahs2-phac:$2y$10$aN91kfzMWy4lj.mTucqtluVKmKkwAJoKuKxH6NkekLjzOl0EMmowu
    cctts-cctt:$2y$10$cpjwdRwQTBzUoqWOby/sQOuVkJcfC05P6DgGTXfmSW5DSNd3dv4Wm
    census-chatbot:$2y$10$Tn.zrHiuq5smokww2.PBYuntHMaQ0igBGxRoizoq.YG/DOf7E6YwO
    charles-belisle:$2y$10$tZ1G1yrTO6D2tBroSffmZ.NAoXvfPrLfIQoktuDkv1znUpGcgtXg2
    charles-belisle-testing-injection:$2y$10$mUwUiBlO.K1kel9aqhdjuOSGK2e01MOyXBkSZPZTC5joKxcWNYmv6
    christian-boin:$2y$10$DgCHyhyKsjH7vV2OA8Pvi.7Zrxvjajuzm9R.DXISvWbUKEebetXKy
    christian-ritter:$2y$10$XRpSuM32H9hvsfqnPGYXwOcQstyZXAzUp54LK945hnIImiP3i8xJ.
    christopher-cottin:$2y$10$fdTXeJU49kYmta1Z7uSVjOqBlSERDpeTjVMtbr.rfBaVyhJwYJsUS
    chuck-novnc-shared:$2y$10$K0KHJJVfRFKjGNBtAP.Gde0zTykmrgiZSkx2EmsaCvLqJ19Jh/TKG
    cloud-native:$2y$10$5LqNgR.d8sSi.1aYjuH/vOlQIPuD/fjsMlTMQHuwxy0m3qZEb6yMS
    codeyan:$2y$10$X5FoxbyizD0JuTuvVM6mq.TCbsMOl7WFdEO707oDOaWj.HQZbNoae
    collin-brown:$2y$10$h1YM5fJ7T8RhrUHs2ntZt.LZWlXIfl5IJhxIXOTA1o.JeoE36U1uu
    constrstarts:$2y$10$7Kf1dauTJ9RFXvEiGA7OBugz7Fymi1AHcLiJUa3Zx0V8vGhNc9wc6
    constructiondetection:$2y$10$JGloV2esT4T7kw0/oldvheOBvNmADQzaefXFKAey3yioxkuN6YX5S
    covid-hubs:$2y$10$lg13GOeIcC39pGORtBravewWWqdsuPMGPznX20ZntQ.BP11.NIhre
    covid-methodology:$2y$10$UALjAewFxeF2jtOKcVK49eiwi2LmaUm.09ABm.cpCM8QJeu0m32B2
    covid-ws-data:$2y$10$83o3WnsbVNBA8vPrrdht6e040R2qH3x0m6bZbmB3fcz0WTS5Q9XSy
    cpddsmlops:$2y$10$rKaQr1UrYW03Vek2o7a.s.YVIaioccuJk7odEZcXq3kASRdfQFCHC
    cphd-data-lab:$2y$10$rZ.WL8Ly5OLWzxMcySgLg.TRi1gczBj02D5o013OVj3GhSUfYooj2
    crop-imaging:$2y$10$.QVpYCLVVwsI2SNL281g7O8F8Nc9sx5.S.FPt.m754LLpmBPxQu6u
    david-kemppainen:$2y$10$TYI79y9FP.pJRp8op3SvDOrS2nS9Ttv9Acku.bXdP0qTYmdMVdC76
    deil-accessibility:$2y$10$Zi62hAg0ZBJRcDQTesGEjOfd7J23epRcNHu7wgIHNq51E7X1weK0y
    deil-lode:$2y$10$BAN3BWvH7V258f7pgghDx.ZjVIdQRw7/n41OLdmPDe37se0TfHqmq
    deil-routing:$2y$10$bKjsxrigzVFAfdgc8jgIJuKSNc3vO6oprblIOK4H6OWEZBn1tOUiW
    dsd-aeas-hydra:$2y$10$VYcaXC23RytzQON1oYY4UOLeRCJfM1NE9gYuFyJkgpi/r3ZT/ju3G
    econ-tracker:$2y$10$iI6zf3cKcm8fACfLdH9PouU1.PUL8rGMK8RKHEFug1UDQPjVwiNtO
    energy-canada:$2y$10$lnwefjXs/hMs8DhIgAxr.O9Rz98fzJk6Efx5U/g67SLo0hD9INjDK
    eventdetec:$2y$10$WQ5ffJFyuK2FdEflaxNqZ.HtLaiJ9pVlyi19wJHO5X3NagKEKssAS
    eventsdetection:$2y$10$o.CZDszM1EJPQo69uzImR.w0QuQKI8fQv5pjc/fheCXKgnKw6oriC
    foo:$2y$10$A4xdt7xWa7DZ.ImuU5Xupe3Pdl1RPGV2brmm321WR3Gn.hnYFoeKm
    frederic-ladouceur:$2y$10$X12atbDgXtnN2tf18iGlMugg6lFShpUsCcaz3/x2zPc1spheWpsKC
    greenhouse-detection:$2y$10$w5yPXwS6AIIRyWzgWMQTC.2ESxXBD8qXnVdUQwIY6DUhOrjUzy5yK
    hilbert-space:$2y$10$9doMckjcFAt7rMsSeyicAerc2uNZAhzJiLxHgLgU.mU8hpPKulCxm
    jessica-barhoma:$2y$10$fGxjH2E4kb91bxPkM9Lv9ODSEEkYB1EO0n5b/K5gZnGIj9bM/UCG2
    jose-matsuda:$2y$10$pgpy2AuclvsxQJiZuz7e3exn5N.nuUu4qaklpFs2XxIrYkdO06HNW
    jose-test:$2y$10$tYsK3uhb72sq8B3mPyYRCOiMZ4QzF6vDdMjBiqRI0zq88KNeY6b4m
    justin-bertrand:$2y$10$/41qrG2FJwhHtHtpVP8mDegGby/4daioXl/lU1Vo8bkkAShomAhuy
    kbf-ns-ym:$2y$10$c8K/nEPwSfTStdYIbBZ/Zu78C7TxVidu1Xasx21R/fxWUJVVTmYxy
    martroc:$2y$10$fV9EDClHrYbklkLH.KK.DORVr9dcfr8isuvRPX5jIKl0uZoujaz3u
    mihir-gajjar:$2y$10$jrEDdrDXeGCjxOmdzqMIiOK5iJwBtZIgzhgidCdwF2pVYxfr7oKwW
    multi-owner-testing:$2y$10$3fZwRPQj3csaDHF1cSE7Xuo5zr3APosQrLFUvlOhxuOVzyeOCjn3G
    nancy-badran:$2y$10$KwU3Vms0MHlEf633p/wdnuWs1iRJcOqGvCtPxBPl2qLh2FAz7zvBi
    nikhil-r-desktop:$2y$10$0v3KMDz1PptJCAniqqyBce81vK952dm0NRcV6.JDnbkt.0Io64AFW
    nikhil-widhani:$2y$10$ngDGSN.8aYUVOXxIyX6jU.DIShOyt3tuxvHUCU6zCqASl38cSp6GC
    nowcasting:$2y$10$qs.kYoX.qKIEp7P8R23YT.25RZ3szS1KQQR459ksOUwcb/Kld0nYe
    nowcastings:$2y$10$aGK1xeYPTngOh60l/ZTueus.atBO.4DOrpDMbtKBM2CAgD5eqymm6
    npp:$2y$10$jMCgh2tsqirPsANh2MM/je4mlo30fJxfr6MXvPbC2WNaw5b4xJ5gS
    nserc-analysis:$2y$10$nb068nKR2txT87ZxmJx0zuhL6FnfQuxQsl9pQIo8.gH7uGcALlG96
    nutrition-ai:$2y$10$FT41QKytzgWBZgFqiMazdumWRFRjYHKhm0v3MmxBKYFhQZbvi.7Ki
    oncosim:$2y$10$1sA41Gsn4Qbh6lc/oLrY0OGgAyqDG5Z3d25s2hmLzjhWjgNxcdS2e
    open-addr-ym:$2y$10$i66kNn8HZzgstMtBFFs42ug52kw5LBnOvTy4U3fFsooKBLHkcyXRC
    pat-ledgerwood:$2y$10$9in7Ow9hPPZcH9TMAxlpDOtoPNDGJeFiql4vJKI3Tqr43ZKFFBv4G
    pat-ledgerwood-statcan:$2y$10$CS9yCdKWt/rk6DMiLlgzq.WDZYHVGXqk5TUU0qllcm3De6Id3giQS
    patrick-paul:$2y$10$R1KjAftbD/1Lh6xSGBuQj.8oKLiE.2j13sxSY44gUANZ49xpNiepu
    pet-lab:$2y$10$x/jFK.k/rAEtCh2HCG1CzOBn2d1wg.1dljlKdSKNCpEZKvjhMy8OO
    poc-nrc-ocrea:$2y$10$HhEQIEyTELosKG7QEYR3eeQ4eFa15smUpaJdmJVmg8kZrNNKrK6Iq
    receipts-ocr:$2y$10$I1BQ010N5iW8cqDl3zfaweZKFF/bjbGVx0MuoLCtj/5NHjrNr2dyu
    reginald-maltais:$2y$10$ZN5DXlseyQWwGCTbEoKiNuVzjzMS.BP0GeA4Q3DOdEo4.ebVEDY6O
    rohan-katkar:$2y$10$BNXrNM7SP.6WlIDIFC6oLus8pWrpILwvkLEgtxEVyDCA6AI5yf/nS
    saffa-alvi:$2y$10$lOSRtUxcL5hWO1QFwVLfU..ylDK3fEhRmFTkOBaJv9Zw/PzY2t5di
    salwa-mohamed:$2y$10$YBePkcl9Z6nl9WN8qsH7d.n5hoHI/Vka8ZK5qGlUMMWa8GI7ONXui
    samd-geofile-process:$2y$10$wATuPkjQ2geCGji0VwQSY.874a4mETOzXSy3AUViLS3eVCRsnynGG
    searchrec:$2y$10$XH1MGPqzU3AasPf9ADshVOkgoNaM42hQLz1UNeMi4rWsrfPlvP/Ue
    seguzac:$2y$10$LczVsBVujDONabTwSpLNZeFcZka6spDwCqNdZhnkcJbgAEa11TjPS
    seguzac2:$2y$10$dsEkNHfgemJVc.nIvrCzSODVztJ3a9RzyM6qbvUl2HKD.dHfJ5Li6
    skye-profile-testing:$2y$10$HzNOm.XXac10VodZw6kV7err486.rEExnwISW3nDhyqL/oCirDy92
    skye-testing:$2y$10$MIa.7iIBpAPuqV5yql9PlOFL.nB7UbJCP2hTxGCvAgNwCv5mVfC3K
    skye-turriff:$2y$10$waARVsMXR2J4rDW.TSeVUOdt8lIyWZ2DneLMUq6n4f61/qCT5xiom
    skye-turriff2:$2y$10$.iEo025QBURHs/pl46J3XeL6InhZKN.8fMyvJd3viEaXaDZxF441.
    souheil-yazji:$2y$10$0LM8uyjr60a23iSjFAbGw.jIf93Iep4bNj8oVaVP9cj.e2wurahkS
    ssc-poc-cfia-bccdc:$2y$10$p1.3UeDw9/ecxyQcnN6WtuSF8/tFSqe.LgWYLHkSY9hfTl1bq0X8a
    ssc-poc-cfia-clb:$2y$10$5jDsC3dxk3QPrXj2979EG.b0TZ.3ND.96HolsrB6aPw9VBO1eAmmW
    ssc-poc-cfia-nrcan:$2y$10$QGCsbStxjPOTC3SpE/Cg2ObpaolGqrNjfUQnXvhKmQsoJaHdN8kYe
    ssc-poc-dfo-csa:$2y$10$5lScbNnWZ9Sp3RkerVfSieMMcZgg9FzTX4NGCYa80cklxt/PQm0Zm
    ssc-poc-nrc-dac:$2y$10$0QAmsqO7wLoyTZ9/8w6TcO7J3wy83b2lzq5K8aMXD9zQ/ScQ1TEHO
    ssc-poc-nrc-nrcan:$2y$10$CWm8iLu2BWl7qs6OENKevuWEfLpflICIusSge4gomSiSxk35gVw52
    ssc-poc-nrcan-cce:$2y$10$95wLWP1zB0ilUXIXB.dLaeTQWjZLrLEk7Qs0TK2eXPN6TxMSI/n9a
    ssc-science-program-team:$2y$10$KKvABgaeUqP7wt3/8s4v1OoKfIu3ZXTUzLJhRCEZq04X8cZjl78L6
    stan-hatko:$2y$10$fBo1rzZj3NP1OJJjKeLwue2avcd8ceBhlwaz4fxTPfDTjPYzClwa2
    stc-expenditure-forecasting:$2y$10$cEv9zw49.F3PxE0wDPlpI.PFtXNVCbHtO0onu.7KdXrhbaDJwko6O
    sy-test:$2y$10$yEMxWD.n/XZkd/B9EFfPgecNT0iSsNVhHXSWXboYflzhx4iQysXR2
    un-pml:$2y$10$MTqki2B1aQZc9UTpPzKlTeoAw8XFZBxr6W5yvJO1ZJHtMb6y1ziya
    vaccineint:$2y$10$5VlL42ctn6CDIR2dD5u50uulBEveaQAzuIOYveq9RHEGVt0vUTfBW
    vedant-vijaythapa:$2y$10$9C7Nd4xtNflisuDQ.HDeA.91EGey0iTZRTb3BKRe9jyeOfjnZtIny
    wendy-gaultier:$2y$10$BlNo0RaOcH8VQQ1BPXxoi.PBnUgPG3RSd30hRCDL0PpE/FBIPclAy
    wendy-gaultier2:$2y$10$UEGPgaLUEddq3zXJrQfJN.5LgJ4rJlfaz2YjObo40XG/tEsPTHCtu
    will-hearn:$2y$10$fQoPw.pclQrGTrm3sMIcG.QvOkyEf8iSe/JBKoFGYMob53SMM.Pxu
    yann-coderre:$2y$10$AglAiEQ6.UHqD3Ojmol4..JiIZkE/CE4ApW/OvyJbo6MaEz8V7iOe
    yie-wang:$2y$10$xjsvTcd04AUJL0vGEvrIfun1JObZAqXHansu2rn4hE9vCbVh60Hcy
    zachary-seguin:$2y$10$nO0TPOKdx60e6KekIsl.CelUuJO8HUGb0yiYNPLn55.Dpziy8jEai
