apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: catalogs
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}

  password.db: |
    aaw-capex:$2y$10$Mb4dwZRJC.BYYc1ZjhS1BeETpLxTOCOG.1XH7YeiPIB6XnurvRcr.
    aaw-fc:$2y$10$RYvRXFyKQtz4N7lXmmd5ZexfUSSqGfgza45XLOkFRJpgL0iHtaDTC
    aaw-pssd:$2y$10$5lYebcOiWXCQ7C1UylxhDef9glJjTrZly4m8cMt8430F83BhHN.VC
    aaw-sedar:$2y$10$aPsgQ/0NFJETNCu/ndaS6.Qm7GwH8tCJVFWFz.nQSt8cHEdozxuXu
    aaw-sedar-app:$2y$10$ToldpzncWjRla4ycWgzpnuaHHW57niCoo26wUVGzUYOP/7RFGXBee
    admin-zachary-seguin:$2y$10$pdLYxkepTr1YgPqpBgwJ2uEXSr.zv9ts5rBxeh6RCgFMWPMpqBgsa
    agzero-avhrr:$2y$10$IH8gl2usbL4933ndM1/12ujcW9Hy5WujkxhFS71Zxjx/XWdbyRWXC
    agzero-crop-intentions:$2y$10$d06BMESJ/L/dlSR.zi6neur3fwNK4Y03jXVSW9HtgPcxD9n7gCrZW
    agzero-march-stocks:$2y$10$oUkVVZE.52oqA3uo2M/RO.26/Ypwof1TsUmZ1N8D/0Pd61ScLHUIa
    agzero-pig-trace:$2y$10$r7iQAaNcFDT/ZOQRzxL6seQDcwyl7HhVQpSoCtWdP9E7MtRV.m8/u
    agzero-poc:$2y$10$v0uHh8id69d2/BdS4gznmOhVu9wrjOHHtGMh9bi3nWlLwb6sgoACu
    agzero-solar-panel:$2y$10$5yyWaCt3Nry7pNLp5jo1weMweUvIBCrqHxtboWVvsNRu/G2R7b1W6
    agzero-yield-model:$2y$10$V2CrhLknxOYioLGN65NzteNZXDCX553fnWtz.g4FhgUVQlctePema
    andres-solismontero:$2y$10$3adLzlE.LLwZX.4LE6VRceInXdGCwc96JCDaA/h9JcA53HmEa1XuC
    andrew-scribner:$2y$10$VqR4kt0gdTPT0XQrinqeEOyy/zvr9CrbVeoSD50wKSjt0VRfGUeEu
    bar:$2y$10$vqkKyjSIk/Ueob2olRvzk.LXOrVHEELFIKvAan4YOPD9czffmEHq2
    bar-rtlbci:$2y$10$9nBPJoRO1nJA92JxQdgMWOhIbnRNOpUFFj5t6.R4mt6w/veKwFpWe
    benjamin-santos:$2y$10$MJg2k4Mv725390xt1PRP6Os.f74g2LdKTW2sKGeG1ytZZ3K8M338a
    bhavika-sewpal:$2y$10$ZzKFL3nJVJ46rL4Eh3lqdujbPk3.UZpUIxgbWu.38I1C1I4Herr32
    blair-drummond:$2y$10$g.9/qNF31jI0RD5MMhUrxu8Srp6AXrniLrWyU3P/sXSLpBXDZ3S3q
    blair-kubeflow-tests:$2y$10$tRHq8pyDxJQ8BIyXAfI6aO/ZC4uhrPWkzrIa4u7lQWDMU7Ms17sci
    blair-shared:$2y$10$TtqksCyOfWpA0ZmAZ/jrceYLlSh3RhiKQtgkyfHISU3IZDMWuikWG
    bob-ross-pics-rise-again:$2y$10$3Qxq62JPvJlaj2y5kxMz9.Rgdz8wbHOAKm0bJ/GPJb84eAppgSzIC
    brendan-gadd:$2y$10$fQ6Vzpru1qL7jvHKlG7dDeDxcMMqZwWP4loKHFbntHdSIgZWnb83u
    brian-chen:$2y$10$K.Pl/nSHtc7aqoAUGoDWheSfNqL83fkODHze2odhOCuMj9wmbvF7m
    bryan-paget:$2y$10$VN17NHE.IRyKbfctwC5zj.IUNYuCl/PWysFOKby.4LjiNAOnyiBHW
    bryanpaget:$2y$10$VHBxV6gSVo9FM0qtL4cQLOpX71ZK6RLZqUwchRZsr7jQbdgcggRli
    building-feat-ext:$2y$10$qWOhozv142s/gas4SQJOUOCksaG1kHvyQlBRgs/EFmTRFAmsMIjqq
    canary:$2y$10$SR9x0XfZ77Y0eWJIBNWp4eGXAoNLjZ12gXxl.ZzmvHhyPDAWrYlo6
    ccahs2-phac:$2y$10$sqANJOkmHTuZzG5WarhfuOUap8gwtGv/FEBnGWMfjMhhWiA2jQwTe
    cctts-cctt:$2y$10$fG67LfWVvC49UXbqFHQQrejO.Uyx3y2YachSA0AXmQjDoxlOqED9O
    census-chatbot:$2y$10$R2TrmioJIDtAqqSrmWsdNuaHKoEUOhB.jvK29ddq/B1N136rzRO3S
    charles-belisle:$2y$10$ocN.TwIp/kEIFfdVxEoLAe.ze0JAFIGQUGJWR6CckBh0oqDwrmI1a
    charles-belisle-testing-injection:$2y$10$uIY.Oj9Sfs7Nlovq4oQ15eKo8prAJemzMnD9Z8lp/NeSm1yoEV7ky
    christian-boin:$2y$10$GqYlZBuirFoMcwI7A8/VAuTG4Y0JPgP7rSGrVkmq3MtJREAwMQx/G
    christian-ritter:$2y$10$7grKt9JClchoamB9Hkv84.VQn58TOMhJXhziNpQBsTkMLX.pEgSDC
    christopher-cottin:$2y$10$E7wztmWvQLdmRPX6aUFHyORkEJfeCG5mCFzsTD2J6TjSuQEo7LyZ.
    chuck-novnc-shared:$2y$10$5QQpQHt6tRmmNCpEcMgX4espsZXpd1.23PEs6yfzbqJlHMSjlGdGG
    cloud-native:$2y$10$CefDdsnAvlZA7wrVJb1kyOq/.F72tKrDWAod8xbaUeAuoDpWqV5eO
    codeyan:$2y$10$ntFO29RkbqXhgqihSWkayuxIW5EUP95aqqAadcSn/caJxI6S.MXeW
    collin-brown:$2y$10$rU1A8S3vRds.0xIv6l50KOp5QlurLN8B0OGV62jOINT89wLVCX6cy
    constrstarts:$2y$10$16S.e3NpyiaixT4xia8QseNXqeo9quxZpOjo00.KGzC8JKmlVeeuG
    constructiondetection:$2y$10$xWmY/HKqgq.zGDrSFp7S6ejnMPkLCgoIW2M.9ONM4.WDYY7EdYndu
    covid-hubs:$2y$10$K2zD0JJwNdqq2pqPvvA8iOKSQ7DTC78h1RuuQVvq9cpDd3kEX/Ddu
    covid-methodology:$2y$10$sbVZlcixIwqSOg/Ko70ZZ.JbAVdy7nyctTMoTzBJY2GBUfXfr3l66
    covid-ws-data:$2y$10$ryr6L1PZVB/odMQ7e/eh1.julRcOs1vImnFP09O47vM2IVw4.Z/qy
    cpddsmlops:$2y$10$5kdenMzCekReOLk905uQSOuKdBXc9qv8yJYYYxSACymMcw5v3JMVC
    cphd-data-lab:$2y$10$F6UXBf23UcIp4mpjRlQCf.r1ewlveAIe.C2Vv3bOwWavvhDz2KiVq
    crop-imaging:$2y$10$8SrCagOJhqTC416Khqa/rOjmDOlwbe4q6gAQB.YpG.ZqiEZphJWzi
    david-kemppainen:$2y$10$L49Q/DrREF6aocRwvkAysOyIwoe7yfO0g.emW/DM7uKmHmFOQ0HTa
    deil-accessibility:$2y$10$fjrdJraV//3QvLnQyIaD8OC.tiYQ2tSApysCTRKivnZWGkwdhfvpa
    deil-lode:$2y$10$/jG.Jol9yvmUTk8975J5DOkcakcoMlq/Ot.4c5ksn0CjIOYzHd6j.
    deil-routing:$2y$10$jydXq1I0X4hKdzmQrRW82.UJKK7FH9WTT8iP31HWc1Jya/677wPpq
    dsd-aeas-hydra:$2y$10$uij/EI7tKz7KvfNloPOwZegNtTwPDcv/hZcv8C/LH0hgX0ZeYLK9q
    econ-tracker:$2y$10$Q4Rl44oWAitugu5JjVNjXe5txbrh1CyeEImWngm9xf3YJW.r/bVTW
    energy-canada:$2y$10$DWgO3RJ0QjdEpkRPIZgyMeKCrh8ltJmw1vjoGjBH.BxZgJ4UxAQk.
    eventdetec:$2y$10$BUaCJshCkMFaorafxXhkveCIz4IsorKF9YsCjJcPzsLnUflUWqEme
    eventsdetection:$2y$10$4WKI73lftfLJEZbR0Zn/l.TQotHXXxAOyFo/52v3ZEl2ANZOxEaZ6
    foo:$2y$10$yWjED1UdYqM7bpvXqWZdaupkyRmVYwPMjDiJxIH1ts//FGD1eOynO
    frederic-ladouceur:$2y$10$epivTrdhS.jklh7D5.vuPOQ0tge/GMOGOQvhoEWPhC4yhraRINv6e
    greenhouse-detection:$2y$10$sPaIIsh70QSfqd6VlkFGIOiHeW4v1EFDmPpOj.yb.oSHHtAuX4R62
    hilbert-space:$2y$10$4lP16GGTm4huaDTHvDHWBOhru2BhxzVMWv1ZoT/Cjjw.PAYgnX6SG
    jessica-barhoma:$2y$10$HZGC/zBaU36HOD.ruRK7w.1kQqL0F5SmS8lTNjnQmhpFx0rAesX.G
    jose-matsuda:$2y$10$KInEa4slDm7CucI4fPiYYOJEVlJzSBVERgrs/6g0SwD7yOp/mfUq2
    jose-test:$2y$10$5L9hPxJn8qG2.98cSxwYFOAOWepWFthDzS3EoNtFAypo6Lt55pPwK
    justin-bertrand:$2y$10$zKO6W/vTZ03PEZzAqEr.zue/YHhmk9FO8Uoq2898gKqhKeGrfRMh2
    kbf-ns-ym:$2y$10$hQWxpKYhmvSrbpHIwMuXvephF8MyQ.b1a8Cpo3cNN1MaOI0.uEu6.
    martroc:$2y$10$Qh/vDD0mSyYpxFmUh0d6EesUId6xuM6Ci8uN62kTC0sUWm6mwvUJ6
    mihir-gajjar:$2y$10$mWzJHSXdWRcgQTVVXb.w0ut/RjUq4MqJtghZqTXwlq2xuFPku/37m
    multi-owner-testing:$2y$10$9Ahc7JR.IQ5xJGyZq4HLheP.txBpgP85ALr30A0sJuo0kLkqkpa.u
    nancy-badran:$2y$10$acILUl3kkw8BkohxZA0zJOhbnf2qyJTjTaAirONMTAKvkYDTanutS
    nikhil-r-desktop:$2y$10$auDF8V51dgvAdUccdfCJae4jybxWHq7dlwBit8UqAm2Dcyo5jf30.
    nikhil-widhani:$2y$10$CdOmh8.FVPIc9kOM1A3xl.2aje7yJitoMULTz7jQZZZlQvbR/nfmG
    nowcasting:$2y$10$VmMZc8GiFSvkzna7RN8AgeostpmS5CGaOuhAoTL2GNPhzYSE5bgEy
    nowcastings:$2y$10$DRUvE.qBWxbuvYFIcl5Y7OOJxeY3WuME8lOWINl7rpweILChRKPdO
    npp:$2y$10$0UtJTisutTMIBC39Pdjmn.Wf/qc7dSDWnNWlA8k2QYZQGBKeeGVau
    nserc-analysis:$2y$10$au1addot5k/IwkMJpLcgZu6qtj5IjQwXqal1rUXcOUKqbnj.4FaLa
    nutrition-ai:$2y$10$s8i4YkLKkCHFFX2YQ7wMUeD7HGTA27X7WngasJQG7B52Tw2DE4Y7e
    oncosim:$2y$10$jhImUoJK0Mlc.lINR2K8Me7ESGSiLxzyZ/uzxtMUa.srb9ONDyRsW
    open-addr-ym:$2y$10$vO19RiBveJw2JCh8nsogVehllTlBg7..WG.qxqk3stcRJgCdNWKp.
    pat-ledgerwood:$2y$10$5GR2fYNSTyNzs4/GKdI0zuZih30EAsGzWv6.06bcZtjOfMbTsOipO
    pat-ledgerwood-statcan:$2y$10$HpMxEzGyzycUJJpJ.jWaKuQtAPo1hTurz2Ae99iyPVCvm/kNma7ia
    patrick-paul:$2y$10$Q8GegrYZJtbB6BewsUWvbe0VT5JN9hLexgEECkCmO9VNUhLXraZ62
    pet-lab:$2y$10$WI1.Q0Sb5rFfIqoghNlwpuVhzhT.qOLVTggQY2b/0O42xi70c8Ol.
    poc-nrc-ocrea:$2y$10$Y5Pyck6uFkDW4ssb3YMezeRbK7YO3AYKiiToWAf0MeweAj1msC2GG
    receipts-ocr:$2y$10$SBe.oTVvGmsvcZuFl4U4kum5Ott6zZWEJLqYSgw1ChpXlUwafZLi6
    reginald-maltais:$2y$10$t63irqR8bDWeX07uC9NZiu4rG7jOnedPydAi4pwJB6nGujBdCQZDu
    rohan-katkar:$2y$10$X.uXDFK0vNQ4ZiCVgNiAe.Z2TqKlInlJN2Q/l34FKVYQYC9LmyEIu
    saffa-alvi:$2y$10$q/gnzUfVO9HjARhZ5jyLjeMmkFZu4EYoAw8DQeqk7/Qrf6gUghrTC
    salwa-mohamed:$2y$10$CjIgQJwGxI4KyogbOm5lCeva1IrQBfajlpyhqX.ph8an3MfkJxgEq
    samd-geofile-process:$2y$10$6C2SqktFAJ0y5K90KrIfjOnebGqQPZhVgwMH4N3Tm7UC6VbRstuvC
    searchrec:$2y$10$1NO1FEwNIE8xbTvkKzceyuiZvndih2udFJE6QjcbKnkNbJIjnh48O
    seguzac:$2y$10$yQSuHONJGZh7cRfkpnD3EeGVSJcWaDgg0.5gSjrQQ7m2FjOwkTde6
    seguzac2:$2y$10$oNz1GoAOCrMkTqcURDvV8.p7GLVg8HSri84RGs7nA0c/Cv/AjdIEW
    skye-profile-testing:$2y$10$x/hzZplUhmnsq.SMnkLCpu5Jq/8b8SXCEhVjIaQ4vIUVL3vrnvBCa
    skye-testing:$2y$10$VkZt50febkmpxNfxw7JUIOiBiEfeN9ILn11BwKNImPMNExEjGQGdO
    skye-turriff:$2y$10$opbyfW9eYfthLsvMywjP6Om/OUZQxnuedfphUT3l5uxY0W2/qeWlm
    skye-turriff2:$2y$10$Ryd1j4DxZGXmPGgn8Q.k2ewcTxbjzqtlhWkwcTQraL8QhHmVlxxqq
    souheil-yazji:$2y$10$2V83RaWiDG.cHoQTLhQQC..62rUDqSg6rOkZ3/K4pBhSLgYG7lL0S
    ssc-poc-cfia-bccdc:$2y$10$gB3zxr5ga80LhT7mLUkhK.XKOTYb3unntAcnVGk0xdE4VNyT/0rQO
    ssc-poc-cfia-clb:$2y$10$WInSrXm5JcPpTbqNhj0JNOFQt1CF8VOGxYXGluQJBRcfQZEMjIMV.
    ssc-poc-cfia-nrcan:$2y$10$K4eqR5oAjYSfxrngMBdzuucXnDS0UziEgqpGZtKewvnvCC2gj7RpG
    ssc-poc-dfo-csa:$2y$10$p3h7d3Zx/tyt0HSFzpRJ4uWk5.gmaMH4hL2759G1ngHOKW5yvywoG
    ssc-poc-nrc-dac:$2y$10$Y6LrVRUT/eWhQdy9dwLs6ucMzRbX6wb4MQaw6GwuRTnQfnaAv8SPK
    ssc-poc-nrc-nrcan:$2y$10$AiPbOgW9n5vhuO7bhrDovulCwagME9gnFaiDIT8A5eLgm.Ex7fbu6
    ssc-poc-nrcan-cce:$2y$10$7nFlbNQeUrfn.IY28Z7JK.9BLMZb/AGT3/vJTKh4ITRzBF3ZExprG
    ssc-science-program-team:$2y$10$N0JBWyHK24Ve9fjSYIvNjOu7KRWxYDY6zgjdfj5DncVq8tz9TQHMC
    stan-hatko:$2y$10$pQc5VDvlA4.wa7u33upX6.kHbC3pD9bQKLkIkhJ9VlrfxMjiGjAdC
    stc-expenditure-forecasting:$2y$10$CX8YKNFe3XYAlNCEQq3FiOZWk8dQirV71JzE/CgVSnXdLQHUTRw6e
    sy-test:$2y$10$aLpxBLCOwFTK/ITyvFvECOXQSD22Q2ZSxH4yKbcFpJ562PDZwozBC
    un-pml:$2y$10$H0R4ZPjJX/zU5o1hoDxeL.6G6OezzXyli5eswEih3Xjx66WXPj96m
    vaccineint:$2y$10$3gtRcs7l2Mi8pe31DLJ7ve8iXXNlJTMotN64UQHlHP4N2NnOcwz0y
    vedant-vijaythapa:$2y$10$ov5c6DYn9JuuE0scZzlhbOtVKD8XvaSAtlSTchuw/Y6D4E9fl8WI6
    wendy-gaultier:$2y$10$1939Y5ZnDXnb3RaBHGTQ8OFoxATUFnkE/mlefoxoZbRv4sSST2qeq
    wendy-gaultier2:$2y$10$Oyd6IejMFTOim4SC/d9Omu60JHlLAWNLxjFjvVcSrUL0vrLXbXX2K
    will-hearn:$2y$10$TVfjJTwNvrcBm.PkhocY2OXHvW2Gul3F/ZT4c4KL7fH.DP2apPkH2
    yann-coderre:$2y$10$cTMogeFiqo1shtTZP29V7ecsicYTeiSIq2yjRJFRlqrc0DI6KXZb.
    yie-wang:$2y$10$5jstmGQsSpdZBYrG3GX2WuBMXIbgjnb1RpFl2v2yxxnqRexRmKQ7C
    zachary-seguin:$2y$10$SwaPeGOrXFR1CgtYXb47Luo.F4gMGvhO01OBjQ3RVTbVmFTx1x7ga
