apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: catalogs
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}

  password.db: |
    aaw-capex:$2y$10$o1PNJWh8mF.kVX0aDMlV9u1BZWpqbuV1cemFiJo//7hTESCqlTTPq
    aaw-fc:$2y$10$pUxagf77YVYwxpixOjFg1.fVFSC3h5H.KkhDp2XS53F.lCcUCLZpe
    aaw-pssd:$2y$10$qco9LkWmqyOAABIyGfQQ0ehV5ykKycqx6Hv7Cd09MJRdnOPJvw5YK
    aaw-sedar:$2y$10$5vflno1TLg6MwTcAiG/VS.a877icqFjN8uY.NMaHLIqwAYpvx19Ei
    aaw-sedar-app:$2y$10$gV0P5M5s/ASKhH/ITrcxTO4EkL3yQkKOu5dk7DPqCybchWt3xspqa
    admin-zachary-seguin:$2y$10$9tUqm3EvsgVfzh6/O3RJyeGcmVJAcNvfpXVbdHr7QXBk7L5W.K/V2
    agzero-avhrr:$2y$10$08.m/Akhol8Tskifh0QXf.AorKrKE83SrtilBT/ChFtSiFYwIgeXu
    agzero-crop-intentions:$2y$10$4ZYSu/jXIOuRNy2aIlHmLuGCOvN4bcCkSqJKUf/TDdYwztULhBkKK
    agzero-march-stocks:$2y$10$MGODXhcsFutu.ktWYOaTQO4GLtz9wqJi/dHCkPhRK1vLeTLqp5L4a
    agzero-pig-trace:$2y$10$dP1COblTJtguT21h1ojVlu2WZxfWUzw/LSg/4IeO.qoG665oOFfge
    agzero-poc:$2y$10$KcQa/E1GINVOqAreYow5feOTneizEvVaPrOaiHljhUVspcEgoNCSe
    agzero-solar-panel:$2y$10$9Yxh8fWzWongwd3.dSFJnu22OfNGuNPRJlO5qdLNJwgieQpElheIS
    agzero-yield-model:$2y$10$fnkmoOTkCxyILbSRNmgUfORGHdsEsYHiQyjpA6VNDp8k2X9M8gMA.
    andres-solismontero:$2y$10$q8sJT3b8bQhOhhedFbmPXOkhRTpwWSVPUgubBScOg3AF9qc4jqYzS
    andrew-scribner:$2y$10$wIpuXj.sEx8VWRJa7Cl9luChAJsZEqFXDgzSntmJs5IoG0K0ZSic.
    bar:$2y$10$vI7kWnOm/thL4ku/bE7ku.TucRbmI0ZNhNUn4PJORfHG16g64dBd.
    bar-rtlbci:$2y$10$1DccW04T5SEyaktf7uevdeN8chQgQtgNNknbshyDwuqYo4CLiYklS
    benjamin-santos:$2y$10$qh6zUOcu/G425PHo5ldwUOmDh2LSiWJdiVFWYbdBn0ZG3J34EQ.m2
    bhavika-sewpal:$2y$10$WIgVLl1.rp32.bxLlNqGQ.Bz1RMcMF9Iz9A7ZV2vdnu24bahKc5f.
    blair-drummond:$2y$10$DZsmtVdk81n7rRzrfUY8AOxLyR3yXvFPo8kqftPZssnxXk8SwsNfe
    blair-kubeflow-tests:$2y$10$2rbH0xvUWifckaVHkR7.fu7GHVXjjKL5b1HizAACclV2.ASK6CxyO
    blair-shared:$2y$10$wRa75uaA/fL3u6gyV/zhX.b5/5Li6MnPMAaq2sfSFjOEarBDjoCT.
    bob-ross-pics-rise-again:$2y$10$b7djIwclwek6jwHd/E..h.H9xOCKyFWk965vdHzfQJwE6Z5N2P1xW
    brendan-gadd:$2y$10$YQUbHC0Gbpl2kwDXqDWEoeZ9fVc9WZtUZrTnUyVoy3NrXxwdEsCbC
    brian-chen:$2y$10$oDj6LB3IY7XghYoWlMItAuuYA9KC4ywcuWUytoI9svLuM/ND9n.9e
    bryan-paget:$2y$10$0Ihl.9/RTlSgCXxdR/tZR.ZptKD1nkRAjZ5EOHKqc.0Y6Ko98FWCi
    bryanpaget:$2y$10$oS7/D1Nclh2tnZ/VqWVDeOM/X.PE7Uv3Bu/GwBsi6n2sxkXQ.OZmi
    building-feat-ext:$2y$10$qfFI5oxwQxr0AYGT6Tw84.gV2fcQImd1mgddz2BERiOPxzOYXE1xy
    canary:$2y$10$ctfTttJ5/TZlEaCNuhE2ZuDE.IcxFVVK5W/T4xanibAOv385vIEKi
    ccahs2-phac:$2y$10$5irWPQZJCm5SBbZVasC.WON91YbDGZ2.XBcR9Xzndv1GSt7AOijHO
    cctts-cctt:$2y$10$EZ96flrnbI.J4Rq05vImzeGyNkbaXe6/h0Q2N3nKXFGXTODQlOohO
    census-chatbot:$2y$10$f4VLYQ7ebyPieM4Jp2W0UehVQmQ.79K2tj2SBew0bcp2BXZd/W1km
    charles-belisle:$2y$10$N7D/aSeYeqvAw3qm0XS0nOBTxiFU59xOMUzsarL5FLm6yQnaCs6SK
    charles-belisle-testing-injection:$2y$10$H6UT/GujUqfklQ3TRfDpu.JyzPbXffRAVfCxdAFxQgxhNMAnGJvUa
    christian-boin:$2y$10$Aw2gOEEIf3bAYpqU4MzcsuuUCPipt7ReLdE9wFN7nYAG/ILPrxfly
    christian-ritter:$2y$10$3absdP2kZoFidr2FnhiXY.cPcmnezOMrNnIvRyUn3aJeRbGnR.fT.
    christopher-cottin:$2y$10$kBOwYSZsRRdS3cORIMl2EettErtMoloHH0vNhLsDQ4XqRyuGZuBWO
    chuck-novnc-shared:$2y$10$/4c4yHbug4om0xbtKtaHPO9qu0263Zuz7nQeIl6kGNcBqlwNBxfRW
    cloud-native:$2y$10$1DJQnT9FrRXY/fNyYop1bO1rMZNRL.rrLTgv5cWGkxlSQ2pYUB7k6
    codeyan:$2y$10$rx32w/.PUARlGcsdVXI3vOIL9JfVF2VREGZ/nBWv3etbWvAwxKP32
    collin-brown:$2y$10$Fnjm43VZujoxTBU0ldCxpuhmHN.cPxEiSlxJ1BchyE.nUc5cTTaWm
    constrstarts:$2y$10$OuuTCliBwww3s521AiQXTupIIT77XkQ6bmRJl85Wx6Ex48N2oaoPK
    constructiondetection:$2y$10$wJXljvybBLCXDgUwKyzUUOJfsQsQDk2hmJLVuXWD7NJWjzwggAO.6
    covid-hubs:$2y$10$yVQMAgZzLJYEHcPle384FOHgEtkY6j7dX9wujthomQJv1zJBf80cC
    covid-methodology:$2y$10$OAsd44UIxTpc2Bm9fxknJe/.Fzqnhxt9MTPK7jOL9qNFrD9VXDE9K
    covid-ws-data:$2y$10$Nkq/A6wpw0YMccbfWXrymunCNPWHpT2D/KiUIZKdCZlfXj4ameTIO
    cpddsmlops:$2y$10$8QUl2c8aBK9SykIVHOyjGedis.6ASZthwmylbpG0sRjNz8IXJFLWK
    cphd-data-lab:$2y$10$LUJywVCwd/.fSe2VhstLNOtWsGRM8obqz/FGxnXXQEHxC9chbZcPy
    crop-imaging:$2y$10$nDZB3Z1CmTeMym/6g2IEUOZBCBoB/LdXKaQ4KUuneVf50dHhPjEc6
    david-kemppainen:$2y$10$pgVG0U2QbzeMuQ8PIWrRVuohtKreueSK4hUM0YEdt.qJc.ZFVEruy
    deil-accessibility:$2y$10$x4dwSYK8pD62rgFCU6xJdOCJgeyDli0bXTI/2.WusmsIQp6dGP.ge
    deil-lode:$2y$10$3oJXQiUoaOOPlPrJTx9Y/uy0R/bhtHavOJOeW.w7eSviZk.p9Vuwi
    deil-routing:$2y$10$ySxYShzM1EnqmZZsfN9s7uzbmHZ2.5uATTKhG291/GSKS.2DQEeNS
    dsd-aeas-hydra:$2y$10$OB/FNTla/2OHn./Zg/r40OEhijIseBYROOAHUJsXjYBs3qNESB7oe
    econ-tracker:$2y$10$sdhMgtU0xgwNnY3hmG.HX.eMPhqFdECZ7KKtzdxfN6ll9oihsj.eq
    energy-canada:$2y$10$m9jV0kbQIIjIPIm/WH/mw.vlqfC44gLtW0IPcZs25GLMMy84WudJq
    eventdetec:$2y$10$KXMO/Uk6OtOFxbwfPkWiVebBA4qMeyF.5Vur.B48koWMfB79n3o8C
    eventsdetection:$2y$10$8TQ9xEyVAv7tj.0dTFEz.e5tJLEscWB/RNTXP82AFNQQkUJ1tcuGu
    foo:$2y$10$5uWbiwpKtP2qeiUhLHTrPOXa28xxIEdQDMzSbo7b5jRKZZaZ3aAqq
    frederic-ladouceur:$2y$10$i3auHCyc8RymCBJEKWCvEuclggkKc6dNkL7HgCcETS1jRO68PPlOC
    greenhouse-detection:$2y$10$r3Eht/u2mZ3iaTymekQ1/.0IezX51OS01nij6j0N7GrLX2iwnxjxi
    hilbert-space:$2y$10$15ZvxtrWyGEjNvSMJW/wfu5liHaTxRQ2QmJ7wYWnPjUfXKJ5f3nfG
    jessica-barhoma:$2y$10$CHrmk01zb2ZXHiYN5fLQpOq3Icor20i4asjni9TrLlW.9/JNoGgv.
    jose-matsuda:$2y$10$k0m04438zPmHsRZOAYTfseMg5Zdo5biYl38t.83MH9/VryziR6NSy
    jose-test:$2y$10$OXPH.WPp/carhrApTbWJlufrZ4JXSflivBlqNI1lpcBAVvoGwluv2
    justin-bertrand:$2y$10$MhNnkevu2om6GEd/6je.LetTbL87qB2o.x0n/fLdOuZN4lF1Y3bom
    kbf-ns-ym:$2y$10$0elI0qerxzeSjBxMnjCfbOokLKABCOQiBMZJpKLPoezs42fOfDMny
    martroc:$2y$10$Knqa7bIsRN9CWbqJ38Bf4eYFeespcgVpdTRi5R6BBDGwP.9Uuj0/W
    mihir-gajjar:$2y$10$BuO45nATb0im.bTqwHRnDOjSwlozUrGjNEWzSK7YVAg.Q.F1/1iqK
    multi-owner-testing:$2y$10$1e3nY/VbKCibEaP0ARn/8eP2No8XKPGNA.Yx628QDFP7Q/acMJpUe
    nancy-badran:$2y$10$r2p2j6/E9sYhrH8FsrAkOuIHoW4rGD1oX4TLnXaqHkpGFeKLdHLoO
    nikhil-r-desktop:$2y$10$g98odkOXttZARWxYWZQTI.WQv3GO8MAyQlX3G04fACw0Ofi2VX1cK
    nikhil-widhani:$2y$10$kEMmfhvKaR9IFvR5FcYQO.hO5n0ZcJjAvG6fnzZCw6kuRMUaISXvG
    nowcasting:$2y$10$NTQOt/EGUpqXUym8s/nv..blawMgPhc8eJlhDKPLK0GEYCdZcpYHi
    nowcastings:$2y$10$sZDlo1KmTwByEwmxENMB2OCUiWVO.Or9i1998VoaOYR6AcTUsqgsO
    npp:$2y$10$lvPr9/76F4XuAOT29lg8FuXeKWG6c46/npy93GwEj0E.fGqZnINsa
    nserc-analysis:$2y$10$x97Okt2oy7zdzjQPBNPCYul43Kzpp7RQkfzQ3TOv5F2t6me3mKqcK
    nutrition-ai:$2y$10$wSl/.b9BDuFeYYfrnTZ50OwmtK6PBoJ7siuCTK.1kFtZ/GTonjkZu
    oncosim:$2y$10$GRLkN4Xwe6lwxQLKS2rxO.ZbU49AAtxDF9cbbJsGxjydvpWli5h6i
    open-addr-ym:$2y$10$sWm7xpzhw6Q1C8MGZPTVw.DuCsXbg.8rmL.Ptb6WIuAUVndQ45gxC
    pat-ledgerwood:$2y$10$ZShLNv7rZ19En/qH99Kc/eYmBtG84o3ZOKE6ng7x0pRH/I13V6Em.
    pat-ledgerwood-statcan:$2y$10$JJVKcUCcy2oidkrk8uLWlOaXRTJfK0HeB.Ljb1NW/DJPTYUl5qaVK
    patrick-paul:$2y$10$AVQIQX29EPi.J9KTE92querXyJr.4BD7LGLU4Q6FvEsla6sPZEroC
    pet-lab:$2y$10$MOUd.eVoqHDEeRnlO3mjEOy89rlS9JYgJz.fqkuKTgbwotHpYM0Zu
    poc-nrc-ocrea:$2y$10$avp2bDHVW/UbTDK5otA39OnoxlOS.JsGxVljYgptjMPNFSvCgaFhK
    receipts-ocr:$2y$10$Q8AtSJDMabZ6oMmV0nlKb.tblUVa9jGQ491Hcg0GpN8S.DjwiHzee
    reginald-maltais:$2y$10$8yxc/ZifsDxTcqMpd77cyeso/7SXEgG.4ue/4KVvuwLXrbSVKzV7K
    rohan-katkar:$2y$10$OVB1x4qAqpqca7ERismFq.T0RqBJ/7IDCFkkVN1i3tHarOkklOO8O
    saffa-alvi:$2y$10$HmdaAmn946RqAyIltC9e3OG6zCAkcs2BFFBlgiQgiFuiKTBN6CSbG
    salwa-mohamed:$2y$10$Zwrsl6V2pbBWTU1/U2QbQe7AC.CIBaxBaoYNRhk0YC.icqHeWu6y.
    samd-geofile-process:$2y$10$3OsMyGP6JFyPNbZB1mP05Oi0fbtr4zJNO4Q6ovX7l0ASnEVjLiafy
    searchrec:$2y$10$DyV28JZ.LXsXPv/4RA9sfuRSIt1EeftKPretcjpdT6kLf0mZ6HPlu
    seguzac:$2y$10$2lLsAezGv.ObL98K/S2S3ue2lTFfRLMw8c.KoRfMdINaEFvH0R3Vq
    seguzac2:$2y$10$cxN4mwDfKtP7W4uwcdJvQeu.v3azc5uSJ52EYkkEKoqhWoOwzWFCS
    skye-profile-testing:$2y$10$NZSzHCTbtlvBRP/iBaLSkuie7ix0YF9qQDKwGgqL8AdeOZdmCJ.UO
    skye-testing:$2y$10$uNStmlbcXlFqdttznRJ4lOGb6zzzuYWhCOjoZiViGwkIB9mvuoys2
    skye-turriff:$2y$10$2y59LAY.uwaEeza78MJkxOPty6qvdz30PnENe2Gw3kM.GFw3Cx.Aa
    skye-turriff2:$2y$10$HjGILge.jCbvbl5RQyzlL.MmeuySzEk0A3KMTSG73ZTwjiX/LX7vm
    souheil-yazji:$2y$10$a9EfR0gP/7001UEnFkqSgeH8EqApcJIMEj09Z47EQ.EsPkfUUgmOO
    ssc-poc-cfia-bccdc:$2y$10$3Bqn7RWHPEzG8woEbjptO.iiFRHY.F6vmdHJcTxtfj44PbVLkTbme
    ssc-poc-cfia-clb:$2y$10$iBfyTjZWNTC71P08XpHoQOE5/ftmLCdPN6Fdw9S44B5ZwQ7s0Lkxq
    ssc-poc-cfia-nrcan:$2y$10$OODv1e3SwSKVTmj3GGuueO3G9BPhuhppCN8nzNP.cY3Jft0U/fbC6
    ssc-poc-dfo-csa:$2y$10$eH9qtnYj4gewVYPO5vIZ..9b8y6La1Bv/v4IHw2auVnTD0N8LYMPe
    ssc-poc-nrc-dac:$2y$10$bmy57iAN3eylJZkif7yg7OyD7zlxSiaaya3NZtcCGDvoImsM3LeBS
    ssc-poc-nrc-nrcan:$2y$10$tR8wY/vr5oJcVSqWIKONduV.jViZp6EbO5lFZ7Bj5mVZm2h8TlzJ.
    ssc-poc-nrcan-cce:$2y$10$zYOV7UqAiyEt223.aMGsaupxsVt0l3dJf7jLcn7mvUtAaZrIJtLmC
    ssc-science-program-team:$2y$10$DmmzDYbhL11iiuCfrYfAo.frrxVVeK9paWwTAFUt/Qh.EwSA5I5oa
    stan-hatko:$2y$10$Lh9via.WopsI70YU2XYPJeVLXtyWukLzz4ZUUq1yFkFg0tdFRClFW
    stc-expenditure-forecasting:$2y$10$RBTd1aTlNX5EfJBO4r4FuOCZJl2fEVDXXY43oUl32P04UPwS.i0si
    sy-test:$2y$10$ihRVIuoOK/HsQ/2L42RWDOByKq4Gup11jJ01c2kZ4YvUAwNM.6gqy
    un-pml:$2y$10$h88Fldt4KSLcXw4CF2iHb.s02YvENvP8wyPHL7XUgIkgaaGxlVTaS
    vaccineint:$2y$10$SvW57SvcXOupCXwBZAJRgeevjujFMw7tz6KgRcw0OcNDGlUhVHSyq
    vedant-vijaythapa:$2y$10$Q81GBbU16xodio6ECSRsmeWF49YSZoPq1/Pz26vN20uoIotQZqb16
    wendy-gaultier:$2y$10$/azsVQzZpH/it1FDfu6kq.oDSQuXFl303aK7vIKAy1LR0tdiu1vIy
    wendy-gaultier2:$2y$10$Mr7Atv2GMy9qVnlakj1iwOAQo.nbJyKHaQBXqhCfF7AOhRnaXbAwO
    will-hearn:$2y$10$yVnjGr8eM0uB9AMX6dHiDuxpJFCiVFjtuXzqUrm6WvCsz7TMC2udW
    yann-coderre:$2y$10$DF.QN3YTLU63n8si11eciuRuSVnx.pjMOc5GWckjMwO3KeVLUMW9W
    yie-wang:$2y$10$Pl.88xPVxWtP6ahWt84HUOBWmm7AclhwYg2/r6HQ29z.PNzoMhA/.
    zachary-seguin:$2y$10$uCOtDsXeIXedAFVaxjJ/b.kb9SjYcC5ei3Mo2sD7YIbp9FY3Q90je
    jose-mastuda2:$2y$10$JAWcX8qeJKwdwOyYX3p91.JWTf8OO0jrK4OI96098qLfZLTON6XJm
