apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-rules
  labels:
    app: trino
    app.kubernetes.io/managed-by: Helm
    chart: trino-0.5.0
    heritage: Helm
    release: trino
    role: catalogs
data:
  rules.json: |
    {
        "schemas": [
            {
                "user": "rohan-katkar",
                "schema": "(rohankatkar|rohankatkar2|rohankatkar3)",
                "owner": true
            },
            {
                "user": "pat-ledgerwood",
                "schema": "patledgerwood",
                "owner": true
            },
            {
                "user": "jose-matsuda",
                "schema": "josematsuda",
                "owner": true
            }
        ],
        "tables": [
            {
              "user": "rohan-katkar",
              "schema": "rohankatkar",
              "table": ".*",
              "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]
              
            },
            {
              "user": "jose-matsuda",
              "schema": "josematsuda",
              "table": ".*",
              "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]  
            },
            {
              "user": "pat-ledgerwood",
              "schema": "patledgerwood",
              "table": ".*",
              "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]  
            }

        ]
    }
    