apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: trino-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
  - to:
    - podSelector: {}
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coordinator-ingress-allow
  namespace: trino-system
spec:
  podSelector:
    matchLabels:
      component: coordinator
  policyTypes:
    - Ingress
  ingress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-hive-allow
  namespace: trino-system
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: hive-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-datasources-allow
  namespace: trino-system
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # TODO: Replace this with CIDRs of StatCan networks.
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: postgresql-datasource
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: minio-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-allow
  namespace: trino-system
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: hive-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
  - to:
    - podSelector: {}
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-trino-to-hive
  namespace: hive-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
  - to:
    - podSelector:
      - namespaceSelector:
        matchLabels:
        kubernetes.io/metadata.name: trino-system
  ingress:
  - from:
    - podSelector:
      - namespaceSelector:
        matchLabels:
        kubernetes.io/metadata.name: trino-system
