apiVersion: v2
appVersion: 3.0.0
description: Apache Hive standalone metastore
home: https://hive.apache.org/
icon: https://hive.apache.org/images/hive_logo_medium.jpg
name: hive-metastore
version: 0.1.0
dependencies:
- name: mariadb
  version: ~11.0.9
  repository: https://charts.bitnami.com/bitnami
